# -*- coding: utf-8; -*-

# SPDX-License-Identifier: GPL-3.0-only

"""Package versions come from poetry.lock, everywhere (user, 2026-10-08).

CI once had no lock file and picked up PySide6 6.12.0 the day it came out;
24 tests that start the program crashed (run 37754952665), and the release
build would have shipped it. So poetry.lock is in the repository, CI and the
release build check it against pyproject.toml and install exactly it, with
the Poetry that wrote it, and this PC's environment is held to it too.
Updating a package is a deliberate step: `poetry update <name>`, CI, commit
the new lock."""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import tomllib
from importlib import metadata
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[2]
_LOCK = _ROOT / "poetry.lock"
_WORKFLOWS = (
    _ROOT / ".github" / "workflows" / "ci.yml",
    _ROOT / ".github" / "workflows" / "release-exe.yml",
)


def _locked() -> dict[str, str]:
    data = tomllib.loads(_LOCK.read_text(encoding="utf-8"))
    return {p["name"].lower(): p["version"] for p in data["package"]}


def _lock_poetry() -> str:
    first = _LOCK.read_text(encoding="utf-8").splitlines()[0]
    match = re.search(r"generated by Poetry (\S+)", first)
    assert match, f"poetry.lock's first line names no Poetry: {first!r}"
    return match.group(1)


def test_the_lock_file_is_kept_in_the_repository() -> None:
    assert _LOCK.is_file(), "poetry.lock is missing: run `poetry lock`"
    ignored = [
        line.strip()
        for line in (_ROOT / ".gitignore").read_text(encoding="utf-8").splitlines()
    ]
    assert "poetry.lock" not in ignored
    if shutil.which("git") and (_ROOT / ".git").exists():
        tracked = subprocess.run(
            ["git", "ls-files", "--error-unmatch", "poetry.lock"],
            cwd=_ROOT, capture_output=True, text=True, timeout=60,
        )
        assert tracked.returncode == 0, "poetry.lock is not committed"


def test_every_dependency_is_locked() -> None:
    project = tomllib.loads((_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    wanted = {
        name.lower()
        for name in project["tool"]["poetry"]["dependencies"]
        if name.lower() != "python"
    }
    missing = sorted(wanted - set(_locked()))
    assert missing == [], f"not in poetry.lock: {missing} (run `poetry lock`)"


@pytest.mark.parametrize("workflow", _WORKFLOWS, ids=lambda p: p.name)
def test_ci_and_the_release_install_exactly_the_lock(workflow: Path) -> None:
    text = workflow.read_text(encoding="utf-8")
    versions = re.findall(r'poetry-version:\s*"?([^"\s]+)"?', text)
    assert versions == [_lock_poetry()], (
        f"{workflow.name}: Poetry {versions}, the lock was written by "
        f"{_lock_poetry()}"
    )
    assert "poetry check --lock" in text
    assert "poetry sync" in text
    assert not re.search(r"poetry install\b", text), (
        f"{workflow.name}: `poetry install` can keep packages the lock dropped; "
        "use `poetry sync`"
    )
    check = text.index("poetry check --lock")
    assert check < text.index("poetry sync")


def test_the_lint_pins_match_the_lock() -> None:
    """CI installs the baseline's pyright and ruff after the lock: they must
    be the locked versions, so the lock stays the whole truth."""
    baseline = json.loads(
        (_ROOT / "tools" / "pyright_baseline.json").read_text(encoding="utf-8")
    )
    pins = baseline.get("versions", {})
    assert pins, "tools/pyright_baseline.json names no tool versions"
    locked = _locked()
    for name, version in pins.items():
        assert locked.get(name.lower()) == version, (
            f"{name}: baseline pins {version}, poetry.lock has "
            f"{locked.get(name.lower())}"
        )


def test_this_environment_has_the_locked_versions() -> None:
    """The PC and CI test what the exe is built from."""
    wrong = []
    for name, version in sorted(_locked().items()):
        try:
            installed = metadata.version(name)
        except metadata.PackageNotFoundError:
            continue  # not for this platform, or an optional extra
        if installed != version:
            wrong.append(f"{name} {installed} (lock {version})")
    assert wrong == [], (
        "installed versions differ from poetry.lock: run `poetry sync`: "
        + ", ".join(wrong)
    )
